# Generated by Django 3.2.9 on 2021-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211128_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel order', 'can cancel order')]},
        ),
    ]
